[package]
name = "horizon"
version = "0.15.2"
edition = "2021"

[dependencies]
clap = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing-subscriber = { workspace = true }
game_server = { path = "../game_server" }
event_system = { path = "../event_system" }
plugin_system = { path = "../plugin_system" }