[package]
name = "horizon"
version = "0.23.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tracing-subscriber = { workspace = true }
game_server = { path = "../game_server" }
horizon_event_system = { path = "../horizon_event_system" }
plugin_system = { path = "../plugin_system" }