[package]
name = "horizon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
types = { path = "../types" }
plugin_system = { path = "../plugin_system" }
event_system = { path = "../event_system" }
tokio-tungstenite = { workspace = true }
futures = { workspace = true }