[workspace]
members = [
    "crates/game_client",
    "crates/server_core",
    "crates/shared_types", 
    "crates/horizon_plugin",
    "crates/game_server"
]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
async-trait = "0.1"
libloading = "0.8"
dashmap = "5.5"
futures = "0.3"
crossbeam = "0.8"
tempfile = "3.5"