[server]
node_id = "default-node"
bind_address = "0.0.0.0:3000"
worker_threads = 4
max_players = 10000
cluster_mode = false
tick_rate = 60
graceful_shutdown_timeout = 30

[network.socketio]
enabled = true
path = "/socket.io"
connection_timeout = 60
heartbeat_interval = 25
heartbeat_timeout = 60
max_payload_size = 1048576

[network.websocket]
enabled = true
path = "/ws"
max_frame_size = 16384
max_message_size = 1048576

[network.http]
enabled = true
api_prefix = "/api/v1"
request_timeout = 30
max_request_size = 10485760
cors_enabled = true
cors_origins = ["*"]

[network.rate_limiting]
enabled = true
requests_per_minute = 600
burst_size = 100
whitelist = ["127.0.0.1", "::1"]

[network.connection_pool]
initial_size = 10
max_size = 100
idle_timeout = 300
max_lifetime = 3600

[world]
default_region_size = 1000.0
max_objects_per_region = 10000
simulation_tick_rate = 60
physics_enabled = true
physics_tick_rate = 60

[world.spatial_index]
rtree_node_capacity = 16
spatial_caching = true
cache_size = 10000
cache_ttl = 300

[world.region_transfer]
enabled = true
timeout = 60
max_concurrent = 5
retry_attempts = 3

[plugins]
directory = "./plugins"
hot_reload = true
scan_interval = 5
timeout = 30
max_memory_usage = 536870912

[plugins.sandbox]
enabled = false
allowed_syscalls = []
network_access = true
filesystem_access = ["./data"]

[monitoring]
enabled = true
metrics_interval = 10

[monitoring.prometheus]
enabled = true
endpoint = "/metrics"
port = 9090

[monitoring.jaeger]
enabled = false
agent_endpoint = "http://localhost:14268/api/traces"
service_name = "horizon2"
sampling_rate = 0.1

[monitoring.health_check]
endpoint = "/health"
interval = 30
timeout = 5

[sharding]
enabled = false
strategy = "Spatial"
replication_factor = 1

[sharding.auto_scaling]
enabled = false
scale_up_threshold = 80.0
scale_down_threshold = 20.0
min_nodes = 1
max_nodes = 10
cooldown = 300

[sharding.consistent_hashing]
virtual_nodes = 150
hash_function = "sha256"

[logging]
level = "info"
format = "Pretty"
structured = true

[logging.output]
type = "Stdout"

[logging.rotation]
enabled = true
max_size = 104857600
max_age = 604800
max_files = 10
compress = true
