[package]
name = "game_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde ={ workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tokio-tungstenite = { workspace = true }
horizon_event_system = { path = "../horizon_event_system" }
plugin_system = { path = "../plugin_system" }
socket2 = "0.5.10"