[package]
name = "game_server"
version = "0.1.0"
edition = "2021"

[dependencies]
server_core = { path = "../server_core" }
shared_types = { path = "../shared_types" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8"
async-trait = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
libloading = { workspace = true }
tokio-tungstenite = { version = "0.26.2" }
crossbeam = { workspace = true }