[package]
name = "horizon_event_system"
version = "0.2.0"
description = "Horizon Event System for handling events in the Horizon game server ecosystem."
license = "MIT"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }